In [1]:
import numpy as np

In [2]:
def Jacobi(A,B,C):
    def Comm(X,Y):
        return X@Y-Y@X
    return(Comm(A,Comm(B,C))+Comm(B,Comm(C,A))+Comm(C,Comm(A,B)))

In [3]:
σx=np.array([[0,1],[1,0]],dtype='complex')
σy=np.array([[0,-1j],[1j,0]],dtype='complex')
σz=np.array([[1,0],[0,-1]],dtype='complex')

In [4]:
Jacobi(σx,σy,σz)

array([[0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j]])

In [5]:
Z=np.random.rand(3,4,4)+1j*np.random.rand(3,4,4)
Z[0]

array([[0.94322578+0.08014634j, 0.71652787+0.43829335j,
        0.95911242+0.06512314j, 0.74440338+0.10510962j],
       [0.35952479+0.12548771j, 0.35071374+0.52336628j,
        0.07027081+0.41563137j, 0.34122548+0.90765142j],
       [0.06044781+0.40048554j, 0.58671061+0.36770455j,
        0.06634219+0.74104357j, 0.02855279+0.97424891j],
       [0.31564692+0.78808385j, 0.71608195+0.6683854j ,
        0.69379196+0.35985371j, 0.83794698+0.96524458j]])

In [6]:
Jacobi(Z[0],Z[1],Z[2])

array([[-4.44089210e-16+8.88178420e-16j, -6.66133815e-16+2.66453526e-15j,
         0.00000000e+00+0.00000000e+00j, -4.44089210e-16+0.00000000e+00j],
       [ 0.00000000e+00-6.66133815e-16j, -1.33226763e-15+1.33226763e-15j,
         8.88178420e-16+4.44089210e-16j,  8.88178420e-16-4.44089210e-16j],
       [ 4.44089210e-16+0.00000000e+00j, -8.88178420e-16-8.88178420e-16j,
         7.77156117e-16+0.00000000e+00j,  1.11022302e-15-8.88178420e-16j],
       [ 1.55431223e-15-8.88178420e-16j, -8.88178420e-16+8.88178420e-16j,
         1.99840144e-15-2.22044605e-16j,  0.00000000e+00-1.77635684e-15j]])

In [7]:
np.sum(Jacobi(Z[0],Z[1],Z[2]))

(2.9976021664879227e-15+4.440892098500626e-16j)

In [ ]:
# Difference between * and @

In [8]:
σx*σx

array([[0.+0.j, 1.+0.j],
       [1.+0.j, 0.+0.j]])

In [9]:
σx@σx

array([[1.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j]])

In [10]:
np.dot(σx,σx)

array([[1.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j]])

In [11]:
def Factorial_1(n):
    Fac=1
    for i in range(1,n+1):
        Fac *= i
        #print(i,Fac)
    return Fac

In [13]:
Factorial_1(4)

24

In [14]:
def Factorial_2(n):
    if n==0:
        return 1
    return n*Factorial_2(n-1)

In [15]:
Factorial_2(5)

120

In [16]:
%timeit Factorial_1(1000)

286 µs ± 3.85 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [17]:
%timeit Factorial_2(1000)

432 µs ± 3.82 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [18]:
import math
%timeit math.factorial(1000)

40.8 µs ± 152 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [19]:
def Factorial_3(n):
    if n==0:
        return 1
    else:
        return np.prod(np.arange(1,n+1)) # We are really making good use of built in functions.

In [20]:
%timeit Factorial_3(1000)

6.15 µs ± 43.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [13]:
x=np.random.rand(100,2,1)

In [14]:
x[2]

array([[0.18864213],
       [0.53975978]])

In [15]:
M=np.random.rand(2,2)

In [18]:
S = M@x

In [22]:
S[99]

array([[0.41536238],
       [0.0891869 ]])